### ISSUE TITLE
Wrong solar declination

### ISSUE THREAD

**Issue by rainman110** [tpl2go/NequickG#1]
Computation of the quotient must be float devision, not int devision:
https://github.com/tpl2go/NequickG/blob/master/NequickG.py#L361

Also, the cosine function in
https://github.com/tpl2go/NequickG/blob/master/NequickG.py#L364

has to be replaced with a sine function (see https://en.wikipedia.org/wiki/Position_of_the_Sun)

**Comment by tpl2go** [comment]
Thank you! Bug has been corrected!

**Comment by rainman110** [comment]
You're welcome ;)
